import = [
  "~/.config/alacritty/color.toml",
  "~/.config/alacritty/keyboard.toml",
]

working_directory = "None"
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 30

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12.0

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
dimensions = { columns = 120, lines = 40 }
dynamic_padding = true
dynamic_title = false
option_as_alt = "OnlyLeft"
padding = { x = 5, y = 5 }
